--データベースを作成
CREATE DATABASE wdb;

--いつテーブルの作成
CREATE TABLE Itsu
(
ID INTEGER NOT NULL,
TEXT VARCHAR(30) NOT NULL,
USER_NAME VARCHAR(30) NOT NULL,
ADD_DATE DATE NOT NULL,
PRIMARY KEY(ID)
);
--どこでテーブルの作成
CREATE TABLE Dokode
(
ID INTEGER NOT NULL,
TEXT VARCHAR(30) NOT NULL,
USER_NAME VARCHAR(30) NOT NULL,
ADD_DATE DATE NOT NULL,
PRIMARY KEY(ID)
);
--だれがテーブルの作成
CREATE TABLE Darega
(
ID INTEGER NOT NULL,
TEXT VARCHAR(30) NOT NULL,
USER_NAME VARCHAR(30) NOT NULL,
ADD_DATE DATE NOT NULL,
PRIMARY KEY(ID)
);
--なにをテーブルの作成
CREATE TABLE Naniwo
(
ID INTEGER NOT NULL,
TEXT VARCHAR(30) NOT NULL,
USER_NAME VARCHAR(30) NOT NULL,
ADD_DATE DATE NOT NULL,
PRIMARY KEY(ID)
);
--完成をテーブルの作成
CREATE TABLE Kansei
(
ID INTEGER NOT NULL,
TEXT VARCHAR(120) NOT NULL,
CREATE_USER VARCHAR(30),
ADD_DATE DATE NOT NULL,
GOOD INTEGER,
PRIMARY KEY(ID)
);